[package]
name = "jsonconv"
version = "0.1.0"
authors = ["Akshara Uke <AKSHARAU@amdocs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
